In [1]:
import numpy as np
import cv2

from feature_tracker import FeatureTrackerTypes, FeatureTracker, FeatureTrackingResult
from feature_orb2D import OrbFeature2D
from feature_matcher import feature_matcher_factory, FeatureMatcherTypes
from parameters import Parameters 
import random
import tracemalloc
import linecache
from visual_odometry import ImageRecievedState, VisualOdometry
from camera import KinectCamera
from utils import compute_euler_angle

In [2]:
MinNumFeatureDefault = Parameters.MinNumFeatureDefault
RatioTest = Parameters.FeatureMatchRatioTest

In [3]:
image_0 = cv2.imread("Images/seq/imagenew0.jpg")
image_1 = cv2.imread("Images/seq/imagenew1.jpg")
image_2 = cv2.imread("Images/seq/imagenew2.jpg")
image_3 = cv2.imread("Images/seq/imagenew3.jpg")

In [4]:
width  = 640
height = 480
fx     = 554.254691191187
fy     = 554.254691191187
cx     = 320.5
cy     = 240.5
D      = [0.0, 0.0, 0.0, 0.0, 0.0] 

In [5]:
cam = KinectCamera(width, height, fx, fy, cx, cy, D)

In [6]:
feature_tracker = FeatureTracker(num_features=MinNumFeatureDefault, 
                       num_levels = 8,  
                       scale_factor = 1.2,   
                       match_ratio_test = RatioTest, 
                       tracker_type = FeatureTrackerTypes.DES_BF)

Using Orb Feature 2D


In [7]:
vo = VisualOdometry(cam, feature_tracker)

In [8]:
vo.cam

In [9]:
vo.trackImage(image_0)

processing first frame


In [10]:
img0 = vo.draw_img

In [12]:
cv2.imwrite("Images/res/image0.jpg", img0)

True

In [10]:
vo.trackImage(image_1)

processing second frame
# matched points:  50 , # inliers:  17


In [14]:
img1 = vo.draw_img

In [15]:
cv2.imwrite("Images/res/image1.jpg", img1)

True

In [16]:
vo.trans_est

array([[ 0.78281471],
       [-0.0212825 ],
       [ 0.62189081]])

In [15]:
cv2.imwrite("Images/current.jpg", img2)

True

In [17]:
print(vo.cur_R)

[[ 0.99959432  0.00204117  0.02840809]
 [-0.00209109  0.99999632  0.00172741]
 [-0.02840446 -0.00178611  0.99959492]]


In [11]:
print(vo.cur_t)

[[ 0.78281471]
 [-0.0212825 ]
 [ 0.62189081]]


In [19]:
vo.poses

[array([[ 0.99959432,  0.00204117,  0.02840809,  0.        ],
        [-0.00209109,  0.99999632,  0.00172741,  0.        ],
        [-0.02840446, -0.00178611,  0.99959492,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])]

In [21]:
vo.trans_est_ref

[[array([0.]), array([0.]), array([0.])]]

In [32]:
compute_euler_angle(vo.cur_R)

array([-0.00492516,  0.0938872 , -0.01327321])

In [12]:
vo.trackImage(image_2)

processing second frame
# matched points:  55 , # inliers:  19


In [13]:
img2 = vo.draw_img
cv2.imwrite("Images/res/image2.jpg", img2)

True

In [16]:
vo.cur_t

array([[1.18445052],
       [0.05603373],
       [1.53442075]])

In [19]:
vo.poses[0]

array([[ 0.99959432,  0.00204117,  0.02840809,  0.        ],
       [-0.00209109,  0.99999632,  0.00172741,  0.        ],
       [-0.02840446, -0.00178611,  0.99959492,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [20]:
vo.poses[1]

array([[ 9.98023904e-01, -3.12445700e-04,  6.28346193e-02,
         4.01635806e-01],
       [ 9.73925527e-04,  9.99944431e-01, -1.04969621e-02,
         7.73162345e-02],
       [-6.28278480e-02,  1.05374154e-02,  9.97968749e-01,
         9.12529933e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [26]:
vo.trans_est_ref

[[array([0.]), array([0.]), array([0.])],
 [array([0.40163581]), array([0.07731623]), array([0.91252993])]]

In [22]:
vo.cur_t

array([[1.18445052],
       [0.05603373],
       [1.53442075]])

In [23]:
vo.cur_R

array([[ 9.98023904e-01, -3.12445700e-04,  6.28346193e-02],
       [ 9.73925527e-04,  9.99944431e-01, -1.04969621e-02],
       [-6.28278480e-02,  1.05374154e-02,  9.97968749e-01]])

In [27]:
vo.trackImage(image_3)

processing second frame
# matched points:  50 , # inliers:  15


In [28]:
img2 = vo.draw_img
cv2.imwrite("Images/res/image2.jpg", img2)

True

In [29]:
vo.trans_est_ref

[[array([0.]), array([0.]), array([0.])],
 [array([0.40163581]), array([0.07731623]), array([0.91252993])],
 [array([0.95375506]), array([-0.00526277]), array([1.74219555])]]

In [30]:
vo.cur_t

array([[ 1.73656977],
       [-0.02654527],
       [ 2.36408636]])

In [31]:
vo.cur_R

array([[ 0.99550813,  0.01321437,  0.09374933],
       [-0.01373435,  0.99989366,  0.00490345],
       [-0.09367457, -0.00616901,  0.99558376]])

In [34]:
img3 = vo.draw_img
cv2.imwrite("Images/res/image3.jpg", img3)

True